version: '2.2'

services:
    postgresql:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=heroes
        ports:
            - 5432:5432

    postgresql-test:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=heroes
        ports:
            - 25432:5432
